name: Build nb-javac and Upload Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Install Ant
      run: sudo apt-get install ant -y

    - name: Clone nb-javac-android
      run: git clone https://github.com/itsaky/nb-javac-android.git

    - name: Build nb-javac
      working-directory: nb-javac-android
      run: ant -f ./make/langtools/netbeans/nb-javac clean jar

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: nb-javac-android
        path: nb-javac-android/make/langtools/netbeans/nb-javac/dist/nb-javac-*-android.jar
